name: publish
on:
  push:
    branches: [ "main" ]

env: 
  REGISTRY: ${{ secrets.DOCKER_USERNAME }}/lol-web-scraper:latest

jobs: 
  publish:
    name: publish-image
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Login 
        run: | 
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and publish
        run: | 
          docker build . --tag ${{ env.REGISTRY }}
          docker push  ${{ env.REGISTRY }}

  deploy: 
    name: deploy-image 
    needs: publish 
    runs-on: ubuntu-latest

    steps: 
     - name: install ssh key 
       run: | 
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
     - name: connect and pull
       run: | 
            ssh root@ ${{ secrets.SSH_HOST }} 
            docker pull ${{ env.REGISTRY }}
     - name: Run the application 
       run: docker run  -p 80:8080 ${{ env.REGISTRY }} 
     - name: cleanup
       run: rm -rf ~/.ssh
