name: publish
on:
  push:
    branches: [ "main" ]

env: 
  REGISTRY: ${{ secrets.DOCKER_USERNAME }}/lol-web-scraper:latest

jobs: 
  publish:
    name: publish-image
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Login 
        run: | 
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and publish
        run: | 
          docker build . --tag ${{ env.REGISTRY }}
          docker push  ${{ env.REGISTRY }}
